# Generated by Django 6.0 on 2026-01-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='user',
            new_name='owner',
        ),
    ]
