# Generated by Django 6.0 on 2026-01-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_user_inventoryitem_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorychangelog',
            old_name='user',
            new_name='changed_by',
        ),
        migrations.RenameField(
            model_name='inventorychangelog',
            old_name='inventory_item',
            new_name='item',
        ),
    ]
